# Generated by Django 3.1.1 on 2022-01-30 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saree_name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('cost', models.CharField(max_length=200)),
                ('added_date', models.DateTimeField(verbose_name='date added')),
            ],
        ),
    ]
