# Generated by Django 2.2.14 on 2022-02-05 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingPage', '0002_auto_20220130_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_path',
            field=models.CharField(default='\\landingPage\\images\\logo.jpg', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='in_stock',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
