# Generated by Django 2.2.14 on 2022-02-18 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingPage', '0003_auto_20220205_1420'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=200)),
                ('ifsc_code', models.CharField(max_length=200)),
                ('account_holder_name', models.CharField(max_length=200)),
                ('bank_name', models.CharField(max_length=200)),
                ('branch', models.CharField(max_length=200)),
                ('is_active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='UPI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upi_id', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('is_active', models.BooleanField()),
            ],
        ),
    ]
